<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            [
                'nombre' => 'Ambientador toque repuesto',
                'descripcion' => 'Ambientador toque repuesto para uso institucional.',
                'precio' => 7000,
                'imagen' => 'img/recurso2.png',
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Ambientador líquido para pisos',
                'descripcion' => 'Ambientador líquido para pisos para uso institucional.',
                'precio' => 7000,
                'imagen' => 'img/recurso1.png',
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Aromática Hindú frutos rojos',
                'descripcion' => 'Aromática Hindú frutos rojos para uso institucional.',
                'precio' => 2500,
                'imagen' => 'img/recurso3.png',
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'Baterias AA',
                'descripcion' => 'Baterias AA para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso5.png',
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Azúcar Incauca',
                'descripcion' => 'Azúcar Incauca para uso institucional.',
                'precio' => 3000,
                'imagen' => 'img/recurso4.png',
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'Baterias AAA',
                'descripcion' => 'Baterias AAA para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso6.png',
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Bolsa aseo blanca 60*60*10',
                'descripcion' => 'Bolsa aseo blanca 60*60*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso7.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa aseo blanca 75*90*10',
                'descripcion' => 'Bolsa aseo blanca 75*90*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso8.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa aseo negra 60*60*10',
                'descripcion' => 'Bolsa aseo negra 60*60*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso9.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Detergente oxigenado 20 Litros',
                'descripcion' => 'Detergente oxigenado 20 Litros para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso14.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Café sello rojo',
                'descripcion' => 'Café sello rojo para uso institucional.',
                'precio' => 9500,
                'imagen' => 'img/recurso13.png',
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'Detergente polvo DERSA 250 gr',
                'descripcion' => 'Detergente polvo DERSA 250 gr para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso15.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Guante eterna cocina antideslizante Talla 8',
                'descripcion' => 'Guante eterna cocina antideslizante Talla 8 para uso institucional.',
                'precio' => 8000,
                'imagen' => 'img/recurso16.png',
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Guante industrial bicolor C35 Talla 7 1/2',
                'descripcion' => 'Guante industrial bicolor C35 Talla 7 1/2 para uso institucional.',
                'precio' => 8000,
                'imagen' => 'img/recurso17.png',
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Bolsa aseo roja 60*60*10',
                'descripcion' => 'Bolsa aseo roja 60*60*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso11.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa aseo roja 75*90*10',
                'descripcion' => 'Bolsa aseo roja 75*90*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso12.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Hipoclorito 13%',
                'descripcion' => 'Hipoclorito 13% para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso18.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Bolsa aseo negra 75*90*10',
                'descripcion' => 'Bolsa aseo negra 75*90*10 para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso10.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Papel higiénico 112 rollos (Paquete x24)',
                'descripcion' => 'Papel higiénico 112 rollos (Paquete x24) para uso institucional.',
                'precio' => 10000,
                'imagen' => 'img/recurso23.png',
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Mecha algodón (Libra)',
                'descripcion' => 'Mecha algodón (Libra) para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso22.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Papel HB institucional 4R (250 MTRS)',
                'descripcion' => 'Papel HB institucional 4R (250 MTRS) para uso institucional.',
                'precio' => 10000,
                'imagen' => 'img/recurso24.png',
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Toalla tisu mano z natural (150)',
                'descripcion' => 'Toalla tisu mano z natural (150) para uso institucional.',
                'precio' => 5000,
                'imagen' => 'img/recurso25.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Vaso desechable 7Oz (50 UND)',
                'descripcion' => 'Vaso desechable 7Oz (50 UND) para uso institucional.',
                'precio' => 4500,
                'imagen' => 'img/recurso26.png',
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'Jabón barra puro 180 gr',
                'descripcion' => 'Jabón barra puro 180 gr para uso institucional.',
                'precio' => 6000,
                'imagen' => 'img/recurso20.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Jabón líquido de manos (Galón)',
                'descripcion' => 'Jabón líquido de manos (Galón) para uso institucional.',
                'precio' => 15000,
                'imagen' => 'img/recurso21.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Jabón antibacterial (Galón)',
                'descripcion' => 'Jabón antibacterial (Galón) para uso institucional.',
                'precio' => 15000,
                'imagen' => 'img/recurso19.png',
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Bolsa negra polietileno alta densidad 60x60 (Paquete x10)',
                'descripcion' => 'Bolsa negra polietileno alta densidad 60x60 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso10.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa negra polietileno alta densidad 75x90 (Paquete x10)',
                'descripcion' => 'Bolsa negra polietileno alta densidad 75x90 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso10.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa gris polietileno alta densidad 60x60 (Paquete x10)',
                'descripcion' => 'Bolsa gris polietileno alta densidad 60x60 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso27.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa blanca polietileno alta densidad 60x60 (Paquete x10)',
                'descripcion' => 'Bolsa blanca polietileno alta densidad 60x60 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso8.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa roja polietileno alta densidad 60x60 (Paquete x10)',
                'descripcion' => 'Bolsa roja polietileno alta densidad 60x60 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso12.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa verde polietileno alta densidad 60x60 (Paquete x10)',
                'descripcion' => 'Bolsa verde polietileno alta densidad 60x60 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso28.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa gris polietileno alta densidad 75x90 (Paquete x10)',
                'descripcion' => 'Bolsa gris polietileno alta densidad 75x90 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso27.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa roja polietileno alta densidad 75x90 (Paquete x10)',
                'descripcion' => 'Bolsa roja polietileno alta densidad 75x90 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso12.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa verde polietileno alta densidad 75x90 (Paquete x10)',
                'descripcion' => 'Bolsa verde polietileno alta densidad 75x90 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso28.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa blanca polietileno alta densidad 75x90 (Paquete x10)',
                'descripcion' => 'Bolsa blanca polietileno alta densidad 75x90 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso8.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Punto ecológico de 3 colores 55 Lts',
                'descripcion' => 'Punto ecológico de 3 colores 55 Lts para uso institucional.',
                'precio' => 120000,
                'imagen' => 'img/recurso29.png',
                'categoria_id' => 7,
            ],
            [
                'nombre' => 'Bolsa negra polietileno alta densidad 90x120 (Paquete x10)',
                'descripcion' => 'Bolsa negra polietileno alta densidad 90x120 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso10.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa blanca polietileno alta densidad 90x120 (Paquete x10)',
                'descripcion' => 'Bolsa blanca polietileno alta densidad 90x120 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso8.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa roja polietileno alta densidad 90x120 (Paquete x10)',
                'descripcion' => 'Bolsa roja polietileno alta densidad 90x120 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso12.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa verde polietileno alta densidad 90x120 (Paquete x10)',
                'descripcion' => 'Bolsa verde polietileno alta densidad 90x120 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso28.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Bolsa gris polietileno alta densidad 90x120 (Paquete x10)',
                'descripcion' => 'Bolsa gris polietileno alta densidad 90x120 (Paquete x10) para uso institucional.',
                'precio' => 4000,
                'imagen' => 'img/recurso27.png',
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Papelera Colplast 22 Lts (colores)',
                'descripcion' => 'Papelera Colplast 22 Lts (colores) para uso institucional.',
                'precio' => 90000,
                'imagen' => 'img/recurso30.png',
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Papelera Colplast 26 Lts (colores)',
                'descripcion' => 'Papelera Colplast 26 Lts (colores) para uso institucional.',
                'precio' => 90000,
                'imagen' => 'img/recurso29.png',
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Papelera Colplast 55 Lts (colores)',
                'descripcion' => 'Papelera Colplast 55 Lts (colores) para uso institucional.',
                'precio' => 90000,
                'imagen' => 'img/recurso30.png',
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Punto ecológico de 4 colores 55 Lts',
                'descripcion' => 'Punto ecológico de 4 colores 55 Lts para uso institucional.',
                'precio' => 120000,
                'imagen' => 'img/recurso32.png',
                'categoria_id' => 7,
            ],
            [
                'nombre' => 'Contenedor 189 Lts (multicolor)',
                'descripcion' => 'Contenedor 189 Lts (multicolor) para uso institucional.',
                'precio' => 90000,
                'imagen' => 'img/recurso33.png',
                'categoria_id' => 7,
            ],
        ];

        foreach ($productos as &$producto) {
            $producto['stock'] = rand(10, 100);
        }

        DB::table('productos')->insert($productos);
    }
}
